project_id = "zsksielzhfezferouztf"

[functions.create-checkout]
verify_jwt = true

[functions.check-payment]
verify_jwt = true

[functions.request-payout]
verify_jwt = true

[functions.create-stripe-product]
verify_jwt = true